[package]
name = "rust-wepapp-playground"
version = "0.1.0"
authors = ["himanoa <matsunoappy@gmail.com>"]

[dependencies]
rocket = { version = "0.3" }
rocket_codegen = { version = "0.3" }
diesel = { version = "<= 1.3", features = ["mysql", "r2d2"] }
