[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--"]

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]
